export const GAME_CONSTANTS = {
    MAX_BLOB_RADIUS: 100,
    BASE_MOVE_SPEED: 1,
    PELLET_COUNT: 20,
    PELLET_RESPAWN_TIME: 5000,
    PELLET_GROWTH_AMOUNT: 3,
    ANIMATION_DURATION: 200,
    FRICTION: 0.98,
    COLLISION_GROWTH_FACTOR: 0.1,
    HAZARDOUS_PELLET_COUNT: 5,
    HAZARD_SHRINK_AMOUNT: 5,
    HAZARD_RESPAWN_TIME: 10000, // 10 seconds
};